CREATE TABLE "user_answers" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_answer" TEXT NOT NULL,
  "question_id" INTEGER REFERENCES "questions"
(id),
  "user_id" INTEGER REFERENCES "user"
(id)
);