CREATE TABLE "user_answers" (
  "id" PRIMARY KEY GENERATED BY DEFAULT AS INTEGER,
  "user_answer" TEXT NOT NULL,
  "question_id" INTEGER REFERENCES "questions"(id),
  "user_id" INTEGER REFERENCES "users"(id)
);